### ISSUE TITLE
Small flux error

### ISSUE THREAD

**Issue by duyhoang-astro** [mhardcastle/radioflux#6]
Hi Martin,

Thanks for sharing the script. I installed this script on my workstation and used it both in ds9 and scripting. I have an issue with flux error. While the flux is calculated correctly, its flux error is always smaller (as compared with CASA). In one of my images (which contains diffuse emission source) it is 5 times smaller. Do you know what could be the reasons for this? Or how do you calculate the flux error?

Thanks,
Duy

**Comment by mhardcastle** [comment]
Hi Duy

Sorry for the delay in replying, I've been away for the last few days.

The flux error is calculated (I believe correctly) by working out the off-source noise using the background region and scaling by the square root of the number of beams across the source. For bright sources it will be an underestimate because the on-source noise tends to exceed the off-source noise -- however, there's no reliable way of estimating the on-source noise, so there's not much that can be done about that. How exactly are you using CASA to measure the noise? Casaviewer, or something else?

Cheers

Martin

**Comment by duyhoang-astro** [comment]
Hi Martin,

Ah, I know what the difference is. I calculated the noise similar to your way (using Casaviewer to get noise rms, beam area, on-source area), but I didn't take square root of the source area (in beam units). This makes my flux error higher. If I take the square root of the source area (in beam units) and multiply it with the noise rms, then I can get back the flux error of this script. Why do we need to take the square root of the source area?

Thanks,
Duy

**Comment by mhardcastle** [comment]
The total flux can be viewed as the sum of the flux from $N$ independent beams each with error sigma where $\sigma$ is the rms off-source noise. By standard rules for the combination of errors the error on the sum is $\sqrt{N\sigma^2} = \sqrt{N}\sigma$.

**Comment by duyhoang-astro** [comment]
Thanks, Martin. I missed this.

**Comment by mhardcastle** [comment]
No worries. Closing this issue.
